server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db?options=-c%20TimeZone=UTC
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    location: classpath:db/migration

security:
  jwt:
    secret: "H7DFRJlgL/nx5ftSvz0r97c7AXeThNITkB5Oy3kuZPg="
    access-token-expiration: 900000
    issuer: auth-service

  cookies:
    secure: false
    same-site: Lax

management:
  endpoints:
    web:
      exposure:
        include: health,info

    endpoint:
      health:
        show-details: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.eventdriven.auth: DEBUG